-- Orders: cache the generated WhatsApp/PDF bill so we don't re-upload a
-- duplicate file every time someone clicks "Send WhatsApp".
--
-- A bill is considered fresh while `bill_generated_at >= updated_at`.
-- Any mutation to the order (status change, item edit, payment, customer
-- detail edit) bumps `updated_at`, which invalidates the cached PDF on the
-- next request. See:
--   - src/lib/bill-generator.ts → getOrGenerateBillUrl
--   - src/app/api/bills/generate/route.ts
--   - src/app/bill/[id]/route.ts (uses bill_generated_at as the ETag key)

ALTER TABLE public.orders
    ADD COLUMN IF NOT EXISTS bill_url TEXT,
    ADD COLUMN IF NOT EXISTS bill_generated_at TIMESTAMPTZ;

COMMENT ON COLUMN public.orders.bill_url IS
    'Canonical proxy URL pointing to the cached bill PDF (e.g. https://<domain>/biil/<id>). Set when the PDF is (re)generated by the web app or the iOS-triggered /api/bills/generate endpoint.';

COMMENT ON COLUMN public.orders.bill_generated_at IS
    'Timestamp of the most recent bill PDF generation. Compared against orders.updated_at to decide whether a new render is needed.';
